#ifndef REPORTSINTERFACE_H
#define REPORTSINTERFACE_H

#include "TableInterface.h"
#include "Category.h"
#include "Invoice.h"
#include "InvoiceItem.h"
#include "Orders.h"
#include "Product.h"
#include "Receipt.h"
#include "Returns.h"
#include "Sales.h"
#include "SalesSummary.h"
#include "Summary.h"

#include <ctime>
#include <sstream>

/// \brief A class to create various reports on the Inventory Management database
///
/// Responsibilities include:
/// - Reporting the total revenue between dates and revenue earned by each catagory in the database
/// - Reporting top sellers in a category between dates
/// - Reporting sales, invoices, and returns between dates
class ReportsInterface {
public:

	/// \brief Reports the total revenue and revenues per category as between two dates
    ///
	/// Calculates the total revenue and the revenue generated by each category between and including 
	/// two dates, startDate and endDate
	/// \param[in] startDate is a string of form "YYYY-MM-DD" representing the beginning of the period
	/// \param[in] endDate is a string of form "YYYY-MM-DD" representing the end of the period
	/// \return A string representing the whole report. It will display all categories, names, and revenues,
	///         as well as total revenue.
	/// \throw DoesNotExistException if nothing is found between startDate and endDate
	virtual string totalRevenueReport(string startDate, string endDate) throw (DoesNotExistException) = 0;

	/// \brief Reports the top sellers between two dates in a specified category
	///
	/// Finds the top selling products by quantity in the category selected between and including
	/// two dates, startDate and endDate (selected by the user)
	/// \param[in] selectedCategory is a string specifying the category chosen by the user
	/// \param[in] startDate is a string of form "YYYY-MM-DD" representing the beginning of the time range
	/// \param[in] endDate is a string of form "YYYY-MM-DD" representing the end of the time range
	/// \return A string representing the whole report. It will display the (top 10) product ID's, 
	///         product names, as well as quantity sold of each product.
	virtual string topSellersReport(string selectedCategory, string startDate, string endDate) = 0;

	/// \brief returns all rows found between two dates using our findIDsBetweenDates function for given table
	///
	/// \pre wrote before findIDsBetweenDates
	/// \param[in] tblTableToReport is a Table for the required search
	/// \param[in] startDate is a string of form "YYYY-MM-DD" representing the beginning of the time range
	/// \param[in] endDate is a string of form "YYYY-MM-DD" representing the end of the time range
	/// \param[in] strColToSearch is the column name of the table that holds the ID
	/// \return a string of all sales between the two given dates
	/// \throw DoesNotExistException if nothing exists between those dates
	virtual string reportBetweenDates(Table tblTableToReport, string startDate, string endDate, string strColToSearch) 
		throw (DoesNotExistException) = 0;

	/// \brief ReportsInterface destructor
	virtual ~ReportsInterface() {};
};

typedef ReportsInterface* Reports;

#endif